"""
Continuous Improvement System
Monitors codebase and automatically suggests improvements
"""

import time
import logging
from pathlib import Path
from typing import Callable, List
from datetime import datetime, timedelta
from architect.agent import ArchitectAgent, Improvement

logger = logging.getLogger(__name__)


class ContinuousImprovementAgent:
    """Agent that continuously monitors and improves the codebase"""
    
    def __init__(self, project_root: str, check_interval: int = 3600):
        """
        Initialize continuous improvement agent
        
        Args:
            project_root: Root directory of the project
            check_interval: Seconds between checks (default: 1 hour)
        """
        self.project_root = Path(project_root)
        self.check_interval = check_interval
        self.architect = ArchitectAgent(str(project_root))
        self.last_analysis = None
        self.improvement_history: List[dict] = []
        self.callbacks: List[Callable] = []
    
    def register_callback(self, callback: Callable[[List[Improvement]], None]):
        """
        Register callback for when improvements are found
        
        Args:
            callback: Function that receives list of improvements
        """
        self.callbacks.append(callback)
    
    def run_analysis(self) -> dict:
        """
        Run single analysis cycle
        
        Returns:
            Analysis results
        """
        logger.info("Running continuous improvement analysis...")
        analysis = self.architect.analyze_project()
        self.last_analysis = datetime.now()
        
        # Store in history
        self.improvement_history.append({
            "timestamp": self.last_analysis.isoformat(),
            "total_issues": analysis['total_issues'],
            "improvements": analysis['improvements']
        })
        
        # Trigger callbacks
        improvements = self.architect.improvements
        if improvements:
            for callback in self.callbacks:
                try:
                    callback(improvements)
                except Exception as e:
                    logger.error(f"Callback error: {e}")
        
        return analysis
    
    def start_monitoring(self):
        """Start continuous monitoring loop"""
        logger.info(f"Starting continuous improvement monitoring (interval: {self.check_interval}s)")
        
        while True:
            try:
                self.run_analysis()
                time.sleep(self.check_interval)
            except KeyboardInterrupt:
                logger.info("Stopping continuous improvement agent...")
                break
            except Exception as e:
                logger.error(f"Error in monitoring loop: {e}")
                time.sleep(60)  # Wait 1 minute before retrying
    
    def get_improvement_trend(self, days: int = 7) -> dict:
        """
        Get improvement trend over time
        
        Args:
            days: Number of days to analyze
            
        Returns:
            Trend analysis
        """
        cutoff = datetime.now() - timedelta(days=days)
        recent = [
            h for h in self.improvement_history
            if datetime.fromisoformat(h['timestamp']) > cutoff
        ]
        
        if not recent:
            return {"message": "No recent analysis data"}
        
        total_issues = [h['total_issues'] for h in recent]
        
        return {
            "period_days": days,
            "analyses_count": len(recent),
            "average_issues": sum(total_issues) / len(total_issues),
            "trend": "improving" if total_issues[-1] < total_issues[0] else "worsening" if total_issues[-1] > total_issues[0] else "stable"
        }


def create_github_issue_callback(token: str, repo: str):
    """
    Create callback that creates GitHub issues for critical improvements
    
    Args:
        token: GitHub personal access token
        repo: Repository in format 'owner/repo'
    """
    def callback(improvements: List[Improvement]):
        critical = [imp for imp in improvements if imp.severity == "critical"]
        if not critical:
            return
        
        import requests
        
        for imp in critical:
            issue_data = {
                "title": f"[Architect] {imp.issue}",
                "body": f"""
## Issue
{imp.issue}

## File
`{imp.file_path}`

## Suggestion
{imp.suggestion}

## Impact
{imp.impact}

## Priority
{imp.priority}/10

---
*Automatically generated by Architect Agent*
                """,
                "labels": ["architect-agent", imp.category, imp.severity]
            }
            
            try:
                response = requests.post(
                    f"https://api.github.com/repos/{repo}/issues",
                    headers={
                        "Authorization": f"token {token}",
                        "Accept": "application/vnd.github.v3+json"
                    },
                    json=issue_data
                )
                if response.status_code == 201:
                    logger.info(f"Created GitHub issue for: {imp.issue}")
            except Exception as e:
                logger.error(f"Failed to create GitHub issue: {e}")
    
    return callback
